name: Rename the project from template

on: [ push ]

permissions: write-all

jobs:
  rename-project:
#    if: ${{ !contains (github.repository, '/FabricKotlinTemplate') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_NAME_SNAKE=$(echo '${{ env.REPOSITORY_NAME }}' | sed -r -e 's/^([A-Z]+)([A-Z])/\L\1\E\2/' -e 's/^[A-Z]/\l&/' -e 's/[A-Z]+$/-\L&/' -e 's/([A-Z]+)([A-Z])/-\L\1\E\2/g' -e 's/[A-Z]/-\l&/g')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Rename the project
        if: steps.is_template.outputs.is_template == 'true'
        run: |
          echo "Renaming the project with -a(author) ${{ env.REPOSITORY_OWNER }} -n(name) ${{ env.REPOSITORY_NAME }} -ns(name snake) ${{ env.REPOSITORY_NAME_SNAKE }} -u(urlname) ${{ env.REPOSITORY_URLNAME }}"
          .github/rename_project.sh -a ${{ env.REPOSITORY_OWNER }} -n ${{ env.REPOSITORY_NAME }} -ns ${{ env.REPOSITORY_NAME_SNAKE }} -u ${{ env.REPOSITORY_URLNAME }} -d "Awesome ${{ env.REPOSITORY_NAME }} created by ${{ env.REPOSITORY_OWNER }}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: init the repository"
          #          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          #          commit_options: '--amend --no-edit'
          push_options: --force
